-- UFC Stats API schema.
-- Safe to run against the existing Supabase database: every table uses
-- CREATE TABLE IF NOT EXISTS, so only the missing fight_stats table is created.
-- events / fighters / fights are reconstructed here for reference and fresh setups.

CREATE TABLE IF NOT EXISTS events (
    id         SERIAL PRIMARY KEY,
    event_name TEXT NOT NULL,
    date       DATE NOT NULL,
    location   TEXT,
    url        TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS fighters (
    id       SERIAL PRIMARY KEY,
    name     TEXT NOT NULL,
    nickname TEXT,
    height   TEXT,
    weight   TEXT,
    reach    INTEGER NOT NULL DEFAULT 0,
    wins     INTEGER NOT NULL DEFAULT 0,
    losses   INTEGER NOT NULL DEFAULT 0,
    draws    INTEGER NOT NULL DEFAULT 0,
    stance   TEXT,
    dob      DATE,
    slpm     DOUBLE PRECISION NOT NULL DEFAULT 0,
    str_acc  INTEGER NOT NULL DEFAULT 0,
    sapm     DOUBLE PRECISION NOT NULL DEFAULT 0,
    str_def  INTEGER NOT NULL DEFAULT 0,
    td_avg   DOUBLE PRECISION NOT NULL DEFAULT 0,
    td_acc   INTEGER NOT NULL DEFAULT 0,
    td_def   INTEGER NOT NULL DEFAULT 0,
    sub_avg  DOUBLE PRECISION NOT NULL DEFAULT 0,
    url      TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS fights (
    id           SERIAL PRIMARY KEY,
    event_id     INTEGER NOT NULL REFERENCES events(id),
    fighter1_id  INTEGER NOT NULL REFERENCES fighters(id),
    fighter2_id  INTEGER NOT NULL REFERENCES fighters(id),
    winner_id    INTEGER REFERENCES fighters(id),
    weight_class TEXT,
    method       TEXT,
    round        INTEGER,
    time         TEXT,
    time_format  TEXT,
    referee      TEXT,
    details      TEXT,
    is_title     BOOLEAN NOT NULL DEFAULT FALSE,
    url          TEXT NOT NULL UNIQUE
);

-- Per-fighter, per-round stats. One row = one fighter in one round of one fight.
-- control_time is stored in seconds. Matches the live Supabase table.
CREATE TABLE IF NOT EXISTS public.fight_stats (
    id                                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fight_id                               BIGINT NOT NULL,
    fighter_id                             BIGINT NULL,
    round_number                           INTEGER NOT NULL,
    knockdowns                             INTEGER NULL,
    sig_strikes_landed                     INTEGER NULL,
    sig_strikes_attempted                  INTEGER NULL,
    total_strikes_landed                   INTEGER NULL,
    total_strikes_attempted                INTEGER NULL,
    total_takedowns_landed                 INTEGER NULL,
    total_takedowns_attempted              INTEGER NULL,
    sub_attempts                           INTEGER NULL,
    reversals                              INTEGER NULL,
    control_time                           INTEGER NULL, -- seconds
    significant_strikes_head_landed        INTEGER NULL,
    significant_strikes_head_attempted     INTEGER NULL,
    significant_strikes_body_landed        INTEGER NULL,
    significant_strikes_body_attempted     INTEGER NULL,
    significant_strikes_leg_landed         INTEGER NULL,
    significant_strikes_leg_attempted      INTEGER NULL,
    significant_strikes_distance_landed    INTEGER NULL,
    significant_strikes_distance_attempted INTEGER NULL,
    significant_strikes_clinch_landed      INTEGER NULL,
    significant_strikes_clinch_attempted   INTEGER NULL,
    significant_strikes_ground_landed      INTEGER NULL,
    significant_strikes_ground_attempted   INTEGER NULL,
    CONSTRAINT fight_stats_pkey PRIMARY KEY (id),
    CONSTRAINT fight_stats_unique UNIQUE (fight_id, fighter_id, round_number),
    CONSTRAINT fight_stats_fight_id_fkey FOREIGN KEY (fight_id) REFERENCES fights (id),
    CONSTRAINT fight_stats_fighter_id_fkey FOREIGN KEY (fighter_id) REFERENCES fighters (id)
);
